@host = localhost
@port = 8081
@baseUrl = http://{{host}}:{{port}}

### Create note
# @name createNote
POST {{baseUrl}}/notes
Content-Type: application/json

{
	"title": "First note",
	"content": "Testing create endpoint",
	"author": "Andrii",
	"is_public": true
}


### Update note (PUT - replace whole note info)
PUT {{baseUrl}}/notes/1908926024183008884
Content-Type: application/json

{
	"title": "Updated note title",
	"content": "Updated note content",
	"author": "Andrii Updated",
	"is_public": false
}

### Modify note (PATCH - partial update)
PATCH {{baseUrl}}/notes/1908926024183008884
Content-Type: application/json

{
	"content": "Patched note content only"
}

### Delete note
DELETE {{baseUrl}}/notes/1908926024183008884
Accept: application/json


### Get note by id
GET {{baseUrl}}/notes/1908926024183008884
Accept: application/json

### Get all notes
GET {{baseUrl}}/notes
Accept: application/json

